/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenObjects {
  LoginResponse: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Post: { // root type
    body?: string | null; // String
    createdAt?: NexusGenScalars['Date'] | null; // Date
    id?: number | null; // Int
    image?: string | null; // String
    title?: string | null; // String
    updatedAt?: NexusGenScalars['Date'] | null; // Date
  }
  Query: {};
  User: { // root type
    createdAt?: NexusGenScalars['Date'] | null; // Date
    email?: string | null; // String
    id?: number | null; // Int
    isAdmin?: boolean | null; // Boolean
    name?: string | null; // String
    password?: string | null; // String
    updatedAt?: NexusGenScalars['Date'] | null; // Date
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  LoginResponse: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['User']; // User!
    createPost: NexusGenRootTypes['Post']; // Post!
    login: NexusGenRootTypes['LoginResponse']; // LoginResponse!
    removePost: string; // String!
    removeProfile: string; // String!
    signup: NexusGenRootTypes['User']; // User!
    updatePost: NexusGenRootTypes['Post']; // Post!
    updateProfile: NexusGenRootTypes['User']; // User!
  }
  Post: { // field return type
    author: NexusGenRootTypes['User']; // User!
    body: string | null; // String
    createdAt: NexusGenScalars['Date'] | null; // Date
    id: number | null; // Int
    image: string | null; // String
    title: string | null; // String
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
  Query: { // field return type
    me: NexusGenRootTypes['User']; // User!
    post: NexusGenRootTypes['Post']; // Post!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
  }
  User: { // field return type
    createdAt: NexusGenScalars['Date'] | null; // Date
    email: string | null; // String
    id: number | null; // Int
    isAdmin: boolean | null; // Boolean
    name: string | null; // String
    password: string | null; // String
    posts: Array<NexusGenRootTypes['Post'] | null>; // [Post]!
    updatedAt: NexusGenScalars['Date'] | null; // Date
  }
}

export interface NexusGenFieldTypeNames {
  LoginResponse: { // field return type name
    token: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    changePassword: 'User'
    createPost: 'Post'
    login: 'LoginResponse'
    removePost: 'String'
    removeProfile: 'String'
    signup: 'User'
    updatePost: 'Post'
    updateProfile: 'User'
  }
  Post: { // field return type name
    author: 'User'
    body: 'String'
    createdAt: 'Date'
    id: 'Int'
    image: 'String'
    title: 'String'
    updatedAt: 'Date'
  }
  Query: { // field return type name
    me: 'User'
    post: 'Post'
    posts: 'Post'
  }
  User: { // field return type name
    createdAt: 'Date'
    email: 'String'
    id: 'Int'
    isAdmin: 'Boolean'
    name: 'String'
    password: 'String'
    posts: 'Post'
    updatedAt: 'Date'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changePassword: { // args
      id: number; // Int!
      newPassword: string; // String!
      oldPassword: string; // String!
    }
    createPost: { // args
      body: string; // String!
      image: string; // String!
      title: string; // String!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    removePost: { // args
      postId: number; // Int!
    }
    removeProfile: { // args
      id: number; // Int!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    updatePost: { // args
      body: string; // String!
      image: string; // String!
      postId: number; // Int!
      title: string; // String!
    }
    updateProfile: { // args
      email: string; // String!
      id: number; // Int!
      name: string; // String!
    }
  }
  Query: {
    post: { // args
      postId: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}